version: '3.7'

services:
  db:
    image: mariadb:10.1.26
    volumes:
      - db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
volumes:
  ? db_data